
services:
  postgres:
    image: postgres:15
    container_name: securelife_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passer
      POSTGRES_DB: SecureLife
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - securelife-net

  redis:
    image: redis:7
    container_name: securelife_redis
    ports:
      - "6379:6379"
    networks:
      - securelife-net

volumes:
  pgdata:

networks:
  securelife-net:
    driver: bridge
